drop table if exists REFRIGERATOR;
drop table if exists FOOD;
drop table if exists SUPPLIER;
drop table if exists PRODUCT;
drop table if exists DILIVER;


CREATE TABLE SUPPLIER
    (SID	INTEGER PRIMARY KEY AUTOINCREMENT,
    SPW		INTEGER		NOT NULL,
    DFEE	INTEGER,
    SNAME	VARCHAR(250),
    UNIQUE(SNAME)
    ); 

CREATE TABLE PRODUCT
    (PID	 	INTEGER PRIMARY KEY AUTOINCREMENT,
    PSID		INTEGER		NOT NULL,
    PNAME		VARCHAR(250),
    PRICE		INTEGER,
    PDATE		INTEGER,
    FOREIGN KEY (PSID) REFERENCES SUPPLIER(SID) ON DELETE CASCADE ON UPDATE CASCADE
    ); 

