drop table if exists FOOD;
drop table if exists SUPPLIER;
drop table if exists PRODUCT;
drop table if exists DILIVER;


Create Table REFRIGERATOR
    (RID			INT			NOT NULL, 	
	 RPW			INT			NOT NULL,
     ADRESS			TEXT,
     AGREE 			INT 		DEFAULT 0,
	PRIMARY KEY(RID),
	 UNIQUE(RID)
);



CREATE TABLE FOOD
    (FID 	INT		NOT NULL,
    FRID	INT,
    FNAME	TEXT,
    CNT	INT,
    FDATE	date,
    PRIMARY KEY(FID),
    UNIQUE(FID),
    FOREIGN KEY(FRID) REFERENCES REFRIGERATOR(RID)
); 



CREATE TABLE SUPPLIER
    (SID	 	INT		NOT NULL,
    SPW		INT		NOT NULL,
    DFEE		INT,
    SNAME		TEXT,
    PRIMARY KEY(SID),
    UNIQUE(SID),
    UNIQUE(SNAME)
    ); 

CREATE TABLE PRODUCT
    (PID	 	INT		NOT NULL,
    PSID		INT		NOT NULL,
    PNAME		TEXT,
    PRICE		INT,
    PDATE		INT,
    PRIMARY KEY(PID),
    UNIQUE(PID),
    FOREIGN KEY (PSID) REFERENCES SUPPLIER(SID)
    ); 



CREATE TABLE DILIVER
    (DID	 	INT		NOT NULL,
    PID		INT		NOT NULL,
    RID		INT		NOT NULL,
    SID		INT		NOT NULL,
    ADRESS			TEXT,
    ORDER_DATE		DATE,
    COST		INT		DEFAULT 0,
    PRIMARY KEY(DID),
    UNIQUE(DID),
    UNIQUE(PID),
    UNIQUE(RID),
    UNIQUE(SID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID)
    FOREIGN KEY (RID) REFERENCES REFRIGERATOR(RID)
    FOREIGN KEY (SID) REFERENCES SUPPLIER(SID)
    ); 
